site_name: Lenguaje de Marcas
site_url: https://estefany89.github.io/MkDocs/
nav:
- Home: INDEX.md
- HTML: HTML.md
- CSS: CSS.md
- XML: XML.md
- GIT: GIT.md
- MARKDOWN: MARKDOWN.md

theme: readthedocs 